create table if not exists public.daderp_rooms (
  code text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.daderp_blocks (
  id uuid primary key default gen_random_uuid(),
  room_code text not null,
  owner_id text not null,
  owner_name text not null,
  x double precision not null,
  y double precision not null,
  z double precision not null,
  size double precision not null default 1,
  color text not null default '#38bdf8',
  collide_self boolean not null default true,
  collide_others boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.daderp_messages (
  id bigint generated by default as identity primary key,
  room_code text not null,
  player_id text not null,
  player_name text not null,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.daderp_rooms enable row level security;
alter table public.daderp_blocks enable row level security;
alter table public.daderp_messages enable row level security;

drop policy if exists "public rooms" on public.daderp_rooms;
drop policy if exists "public blocks" on public.daderp_blocks;
drop policy if exists "public messages" on public.daderp_messages;

create policy "public rooms" on public.daderp_rooms for all to anon, authenticated using (true) with check (true);
create policy "public blocks" on public.daderp_blocks for all to anon, authenticated using (true) with check (true);
create policy "public messages" on public.daderp_messages for all to anon, authenticated using (true) with check (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.daderp_blocks;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.daderp_messages;
  exception when duplicate_object then null;
  end;
end $$;
